name: Add Review Template

on: 
  pull_request:
    types:
      - labeled
      
permissions:
  contents: read

jobs:
  comment-that-approved: 
    runs-on: ubuntu-latest
    steps:
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Runner
        path: |
          /.github/workflows/CI.yml
          /.github/workflows/learn-github-action.yml
        
      
